export const data = [
    {
      name: "raw_sales_0",
      type: "source",
      depends_on: [],
      tests_passed: 5,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_sales_1",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_sales_2",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 8,
    },
    {
      name: "raw_sales_3",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 3,
      tests_warned: 0,
    },
    {
      name: "raw_sales_4",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 7,
    },
    {
      name: "raw_marketing_0",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 7,
    },
    {
      name: "raw_marketing_1",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_marketing_2",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_finance_0",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 6,
    },
    {
      name: "raw_finance_1",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_finance_2",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_hr_0",
      type: "source",
      depends_on: [],
      tests_passed: 8,
      tests_failed: 5,
      tests_warned: 0,
    },
    {
      name: "raw_hr_1",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_hr_2",
      type: "source",
      depends_on: [],
      tests_passed: 4,
      tests_failed: 7,
      tests_warned: 0,
    },
    {
      name: "raw_hr_3",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_hr_4",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_rnd_0",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_rnd_1",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_rnd_2",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_rnd_3",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_support_0",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 8,
      tests_warned: 0,
    },
    {
      name: "raw_support_1",
      type: "source",
      depends_on: [],
      tests_passed: 3,
      tests_failed: 0,
      tests_warned: 5,
    },
    {
      name: "raw_support_2",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_bd_0",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_bd_1",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "raw_bd_2",
      type: "source",
      depends_on: [],
      tests_passed: 4,
      tests_failed: 0,
      tests_warned: 9,
    },
    {
      name: "raw_bd_3",
      type: "source",
      depends_on: [],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_orders",
      type: "model",
      depends_on: ["raw_sales_0", "raw_sales_4", "raw_sales_2", "raw_sales_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_customers",
      type: "model",
      depends_on: [
        "raw_sales_3",
        "raw_sales_2",
        "raw_sales_4",
        "raw_sales_0",
        "raw_sales_1",
      ],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 6,
    },
    {
      name: "sales_pipeline",
      type: "model",
      depends_on: ["raw_sales_3", "raw_sales_2", "raw_sales_4", "raw_sales_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 7,
    },
    {
      name: "sales_opportunities",
      type: "model",
      depends_on: ["raw_sales_1", "raw_sales_2", "raw_sales_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_leads",
      type: "model",
      depends_on: ["raw_sales_2", "raw_sales_4", "raw_sales_1"],
      tests_passed: 4,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_funnel",
      type: "model",
      depends_on: ["raw_marketing_0", "raw_marketing_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_attribution",
      type: "model",
      depends_on: ["raw_marketing_2", "raw_marketing_1", "raw_marketing_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_events",
      type: "model",
      depends_on: ["raw_marketing_0", "raw_marketing_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_campaigns",
      type: "model",
      depends_on: ["raw_marketing_1", "raw_marketing_2", "raw_marketing_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_creatives",
      type: "model",
      depends_on: ["raw_marketing_2", "raw_marketing_1", "raw_marketing_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_expenses",
      type: "model",
      depends_on: ["raw_finance_0", "raw_finance_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_income",
      type: "model",
      depends_on: ["raw_finance_0", "raw_finance_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_taxes",
      type: "model",
      depends_on: ["raw_finance_1", "raw_finance_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 8,
    },
    {
      name: "finance_reports",
      type: "model",
      depends_on: ["raw_finance_0", "raw_finance_2", "raw_finance_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_investments",
      type: "model",
      depends_on: ["raw_finance_0", "raw_finance_2", "raw_finance_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_budget",
      type: "model",
      depends_on: ["raw_finance_2", "raw_finance_0", "raw_finance_1"],
      tests_passed: 3,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_employees",
      type: "model",
      depends_on: ["raw_hr_4", "raw_hr_0", "raw_hr_3", "raw_hr_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_vacations",
      type: "model",
      depends_on: ["raw_hr_4", "raw_hr_0"],
      tests_passed: 0,
      tests_failed: 6,
      tests_warned: 0,
    },
    {
      name: "hr_gifts",
      type: "model",
      depends_on: ["raw_hr_2", "raw_hr_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_team_outings",
      type: "model",
      depends_on: ["raw_hr_1", "raw_hr_2", "raw_hr_4", "raw_hr_0", "raw_hr_3"],
      tests_passed: 3,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_swag",
      type: "model",
      depends_on: ["raw_hr_4", "raw_hr_0", "raw_hr_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_logistics",
      type: "model",
      depends_on: ["raw_hr_3", "raw_hr_0", "raw_hr_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_office_supplies",
      type: "model",
      depends_on: ["raw_hr_3", "raw_hr_0", "raw_hr_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_user_events",
      type: "model",
      depends_on: ["raw_rnd_0", "raw_rnd_3", "raw_rnd_2", "raw_rnd_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_deployments",
      type: "model",
      depends_on: ["raw_rnd_1", "raw_rnd_3"],
      tests_passed: 4,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_incidents",
      type: "model",
      depends_on: ["raw_rnd_2", "raw_rnd_0", "raw_rnd_3"],
      tests_passed: 4,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_uptime",
      type: "model",
      depends_on: ["raw_rnd_3", "raw_rnd_2", "raw_rnd_1", "raw_rnd_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_pull_requests",
      type: "model",
      depends_on: ["raw_rnd_2", "raw_rnd_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 9,
    },
    {
      name: "rnd_libraries",
      type: "model",
      depends_on: ["raw_rnd_0", "raw_rnd_1", "raw_rnd_3"],
      tests_passed: 3,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "support_tickets",
      type: "model",
      depends_on: ["raw_support_2", "raw_support_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "support_customers",
      type: "model",
      depends_on: ["raw_support_0", "raw_support_1", "raw_support_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "support_agents",
      type: "model",
      depends_on: ["raw_support_0", "raw_support_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 3,
    },
    {
      name: "bd_partners",
      type: "model",
      depends_on: ["raw_bd_0", "raw_bd_3", "raw_bd_1", "raw_bd_2"],
      tests_passed: 0,
      tests_failed: 3,
      tests_warned: 0,
    },
    {
      name: "bd_events",
      type: "model",
      depends_on: ["raw_bd_0", "raw_bd_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "bd_partnerships",
      type: "model",
      depends_on: ["raw_bd_2", "raw_bd_3", "raw_bd_1", "raw_bd_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 3,
    },
    {
      name: "sales_joined_0",
      type: "model",
      depends_on: ["sales_leads", "raw_sales_4"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_joined_1",
      type: "model",
      depends_on: [
        "sales_opportunities",
        "sales_pipeline",
        "sales_customers",
        "raw_sales_4",
      ],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 4,
    },
    {
      name: "sales_joined_2",
      type: "model",
      depends_on: ["sales_pipeline", "sales_leads", "sales_opportunities"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_final_0",
      type: "model",
      depends_on: ["sales_orders", "raw_sales_2"],
      tests_passed: 3,
      tests_failed: 6,
      tests_warned: 9,
    },
    {
      name: "sales_final_1",
      type: "model",
      depends_on: ["sales_customers"],
      tests_passed: 4,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_full_0",
      type: "model",
      depends_on: [
        "marketing_campaigns",
        "marketing_creatives",
        "marketing_events",
        "raw_marketing_0",
      ],
      tests_passed: 7,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_full_1",
      type: "model",
      depends_on: ["marketing_creatives"],
      tests_passed: 0,
      tests_failed: 8,
      tests_warned: 4,
    },
    {
      name: "marketing_full_2",
      type: "model",
      depends_on: [
        "marketing_funnel",
        "marketing_attribution",
        "raw_marketing_1",
      ],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_final_0",
      type: "model",
      depends_on: ["marketing_events", "raw_marketing_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 6,
    },
    {
      name: "marketing_final_1",
      type: "model",
      depends_on: ["marketing_creatives", "marketing_funnel"],
      tests_passed: 4,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_final_2",
      type: "model",
      depends_on: ["marketing_campaigns", "marketing_attribution"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_final_3",
      type: "model",
      depends_on: ["marketing_attribution"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_joined_0",
      type: "model",
      depends_on: ["finance_budget", "finance_income", "raw_finance_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_joined_1",
      type: "model",
      depends_on: ["finance_investments", "finance_income", "raw_finance_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_final_0",
      type: "model",
      depends_on: ["finance_budget", "finance_expenses"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_final_1",
      type: "model",
      depends_on: ["finance_budget"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_full_0",
      type: "model",
      depends_on: ["hr_employees", "hr_gifts"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_full_1",
      type: "model",
      depends_on: ["hr_swag", "hr_vacations", "raw_hr_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_full_2",
      type: "model",
      depends_on: ["hr_vacations"],
      tests_passed: 0,
      tests_failed: 3,
      tests_warned: 0,
    },
    {
      name: "hr_full_3",
      type: "model",
      depends_on: ["hr_employees", "hr_logistics", "raw_hr_3"],
      tests_passed: 0,
      tests_failed: 5,
      tests_warned: 0,
    },
    {
      name: "hr_full_4",
      type: "model",
      depends_on: ["hr_team_outings", "hr_office_supplies", "raw_hr_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 5,
    },
    {
      name: "hr_final_0",
      type: "model",
      depends_on: ["hr_team_outings", "hr_swag", "hr_employees", "raw_hr_1"],
      tests_passed: 8,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_final_1",
      type: "model",
      depends_on: ["hr_gifts", "hr_vacations", "hr_logistics", "raw_hr_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_full_0",
      type: "model",
      depends_on: ["rnd_user_events", "rnd_incidents", "raw_rnd_3"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_joined_0",
      type: "model",
      depends_on: ["rnd_pull_requests"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_joined_1",
      type: "model",
      depends_on: ["rnd_pull_requests"],
      tests_passed: 7,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_joined_2",
      type: "model",
      depends_on: ["rnd_pull_requests", "rnd_deployments", "rnd_user_events"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_final_0",
      type: "model",
      depends_on: ["rnd_pull_requests"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_final_1",
      type: "model",
      depends_on: ["rnd_incidents", "raw_rnd_1"],
      tests_passed: 5,
      tests_failed: 9,
      tests_warned: 7,
    },
    {
      name: "rnd_final_2",
      type: "model",
      depends_on: ["rnd_uptime"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "rnd_final_3",
      type: "model",
      depends_on: ["rnd_user_events", "raw_rnd_1"],
      tests_passed: 9,
      tests_failed: 6,
      tests_warned: 0,
    },
    {
      name: "rnd_final_4",
      type: "model",
      depends_on: ["rnd_user_events", "rnd_deployments"],
      tests_passed: 6,
      tests_failed: 0,
      tests_warned: 7,
    },
    {
      name: "support_full_0",
      type: "model",
      depends_on: ["support_customers", "support_tickets", "raw_support_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "support_joined_0",
      type: "model",
      depends_on: ["support_tickets", "support_customers"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "support_joined_1",
      type: "model",
      depends_on: ["support_tickets", "support_agents"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "support_final_0",
      type: "model",
      depends_on: ["support_tickets", "support_agents", "raw_support_2"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "bd_joined_0",
      type: "model",
      depends_on: ["bd_events", "bd_partnerships", "bd_partners"],
      tests_passed: 0,
      tests_failed: 5,
      tests_warned: 6,
    },
    {
      name: "bd_joined_1",
      type: "model",
      depends_on: ["bd_partnerships", "raw_bd_3"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_dashboard",
      type: "exposure",
      depends_on: ["sales_joined_2", "sales_pipeline"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "sales_report",
      type: "exposure",
      depends_on: [
        "sales_opportunities",
        "sales_customers",
        "sales_joined_1",
        "sales_leads",
      ],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_report",
      type: "exposure",
      depends_on: ["marketing_events", "marketing_campaigns"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "marketing_dashboard",
      type: "exposure",
      depends_on: [
        "marketing_full_2",
        "marketing_funnel",
        "marketing_final_0",
        "marketing_final_1",
      ],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "finance_report",
      type: "exposure",
      depends_on: ["finance_reports", "finance_investments", "finance_budget"],
      tests_passed: 0,
      tests_failed: 6,
      tests_warned: 6,
    },
    {
      name: "hr_report",
      type: "exposure",
      depends_on: ["hr_full_2", "hr_full_0", "hr_final_0", "hr_employees"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "hr_dashboard",
      type: "exposure",
      depends_on: ["hr_full_0", "hr_office_supplies", "hr_vacations"],
      tests_passed: 0,
      tests_failed: 7,
      tests_warned: 0,
    },
    {
      name: "rnd_report",
      type: "exposure",
      depends_on: ["rnd_libraries", "rnd_final_3", "rnd_joined_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 6,
    },
    {
      name: "support_report",
      type: "exposure",
      depends_on: [
        "support_customers",
        "support_full_0",
        "support_tickets",
        "support_agents",
      ],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "bd_report",
      type: "exposure",
      depends_on: ["bd_events", "bd_partnerships", "bd_joined_0"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 0,
    },
    {
      name: "bd_dashboard",
      type: "exposure",
      depends_on: ["bd_joined_0", "bd_partners", "bd_joined_1"],
      tests_passed: 0,
      tests_failed: 0,
      tests_warned: 6,
    },
  ];
  